MVC/Models/DeviceModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Android_Push_Notifications.Models
{
    public class DeviceModel
    {
        [Required]
        [Display(Name = "Registration Id")]
        [DataType(DataType.Text)]
        public string RegistrationId { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Imei { get; set; }
    }
}

MVC/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Android_Push_Notifications.Models
{
    public class UserModel
    {
        [Required]
        [DataType(DataType.Text)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Length must be from 3 to 50 symbols")]
        public string Login { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public  ICollection<DeviceModel> Devices { get; set; }
    }
}

MVC/Controllers/DeviceController.cs
using Android_Push_Notifications.Models;
using BLL.Entites;
using BLL.Interfaces.Services;
using DAL.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Android_Push_Notifications.Controllers
{
    public class DeviceController : Controller
    {
        // [Inject]
        IDeviceService _deviceService;
        INotificationService _notificationService;

        public DeviceController(IDeviceService deviceService, INotificationService notificationService)
        {
            _deviceService = deviceService;
            _notificationService = notificationService;
        }
        
        public ActionResult SendNotification(DeviceModel deviceModel, string message)
        {
            var device = AutoMapper.Mapper.Map<Device>(deviceModel);
            var responce = _notificationService.sendNotification(device, message);
            ViewBag.responce = responce;
            return PartialView("SendNotification", deviceModel);
        }

        public ActionResult AddNotification(DeviceModel device)
        {
           return PartialView("SendNotification", device);
        }

        // GET 
        public ActionResult Devices(UserModel userModel )
        {
            var devices = userModel.Devices;
            return PartialView("Devices",devices);
        }    
    }
}

MVC/Controllers/UserController.cs
using Android_Push_Notifications.Models;
using BLL.Interfaces.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Entites;

namespace Android_Push_Notifications.Controllers
{
    public class UserController : Controller
    {
       // [Inject]
        IDeviceService _deviceService;
        //[Inject]
        IUserService _userService;

        public UserController(IDeviceService deviceService, IUserService userService)
        {
            _deviceService = deviceService;
            _userService = userService;
        }
        
        // GET: User
        public ActionResult Index()
        {
            var users = _userService.GetAll();
            var usersModel = AutoMapper.Mapper.Map<IEnumerable<User>, IEnumerable<UserModel>>(users);
            return View(usersModel);
        }
        
        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Login,Password")] UserModel userModel)
        {
            if(ModelState.IsValid)
            {
                var user = AutoMapper.Mapper.Map<User>(userModel);
                _userService.Create(user,userModel.Password);
                
            }
            return RedirectToAction("Index");
        }

        
    }
}

MVC/Views/Device/Devices.cshtml
@model IEnumerable<Android_Push_Notifications.Models.DeviceModel>


<div class="panel panel-default">
  
    <div>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.RegistrationId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imei)
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.RegistrationId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Imei)
                    </td>

                    <td>
                        @Html.ActionLink("Send Notification", "AddNotification","Device", item, new { data_modal = "", @class = "btn btn-primary pull-right" })
                       
                    </td>


                </tr>
            }

        </table>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/modalform")
}

MVC/Views/Device/SendNotification.cshtml
@model Android_Push_Notifications.Models.DeviceModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Send Notification</h4>
</div>


@using (Html.BeginForm("SendNotification", "Device", Model ,FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="modal-body">
        
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
           
            <div class="form-group">
                
                <div class="col-md-12">
                    <p> Message </p> @Html.TextBox("message", null, new { @class = "form-control" })
                     
                    
                </div>
            </div>
    </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Cancel</button>
        <input class="btn btn-primary" type="submit" value="Send Notification" />
    </div>
}
<div>
    Responce: @ViewBag.responce
</div>

MVC/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -  ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modalform")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Android Push Notifications", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Create new user", "Create", "User") </li>
</ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -ASP.NET Application</p>
        </footer>
    </div>

@Scripts.Render("~/bundles/bootstrap")
</body>
</html>

MVC/Views/User/Create.cshtml
@model Android_Push_Notifications.Models.UserModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create user</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login)
                @Html.ValidationMessageFor(model => model.Login)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
       
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
    
</div>

MVC/Views/User/Index.cshtml
@model IEnumerable<Android_Push_Notifications.Models.UserModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

    @using (Html.BeginForm())
{
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>UserModel</h4>
            <hr />
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Login)
                    </th>

                    <th>Devices</th>
                </tr>

                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Login)
                        </td>

                        <td>
                            @Html.Action("Devices", "Device", item)
                        
                        </td>
                    </tr>
            }
            </table>

            </div>
            }

           